name: .NET Tests

on:
  push:
    branches: [ main, labs ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./Library/Library.sln

      - name: Build
        run: dotnet build ./Library/Library.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./Library/Library.Tests/Library.Tests.csproj --configuration Release --verbosity normal